name: AOTM Client

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Build
        id: export
        uses: firebelley/godot-export@master
        with:
            godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.2/rc1/Godot_v3.5.2-rc1_linux_headless.64.zip
            godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.2/rc1/Godot_v3.5.2-rc1_export_templates.tpz
            relative_project_path: ./Client
            relative_export_path: ./my/build/destination # move export output to this directory relative to git root
            archive_output: true
            export_debug: true
            use_godot_4: false
      - name: Upload Windows
        uses: actions/upload-artifact@v2
        with:
          name: AOTM Client - Windows
          path: ${{ steps.export.outputs.archive_directory }}/Client_Windows.zip
      - name: Upload Mac
        uses: actions/upload-artifact@v2
        with:
          name: AOTM Client - Linux
          path: ${{ steps.export.outputs.archive_directory }}/Client_Linux.zip
      - name: Upload Linux
        uses: actions/upload-artifact@v2
        with:
          name: AOTM Client - MacOS
          path: ${{ steps.export.outputs.archive_directory }}/Client_MacOS.zip
      - name: Upload Web
        uses: actions/upload-artifact@v2
        with:
          name: AOTM Client - Web
          path: ${{ steps.export.outputs.archive_directory }}/Client_Web.zip