name: Build Godot

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2
      - name: get tag from version
        id: tag_version
        run: |
          echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: install wine
        id: wine_install
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
      - name: export game
        id: export
        uses: firebelley/godot-export@master
        with:
            godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/beta8/Godot_v4.0-beta8_linux.x86_64.zip
            godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/beta8/Godot_v4.0-beta8_export_templates.tpz
            relative_project_path: ./
            relative_export_path: ./my/build/destination # move export output to this directory relative to git root
            archive_output: true
            wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
            use_godot_4: true
      - name: Upload Windows
        uses: actions/upload-artifact@v2
        with:
          name: AOTM - Windows
          path: ${{ steps.export.outputs.archive_directory }}/AOTM.exe
      - name: Upload Mac
        uses: actions/upload-artifact@v2
        with:
          name: AOTM - MacOS
          path: ${{ steps.export.outputs.archive_directory }}/AOTM.x86_64
      - name: Upload Linux
        uses: actions/upload-artifact@v2
        with:
          name: AOTM - Linux
          path: ${{ steps.export.outputs.archive_directory }}/AOTM.zip
      - name: Upload Web
        uses: actions/upload-artifact@v2
        with:
          name: AOTM - Web
          path: ${{ steps.export.outputs.archive_directory }}/AOTM.html
